# database
jamalese_to_english = {
    "a": "a",
    "add": "add, addition",
    "ainii": "any",
    "and": "and",
    "andrstan": "understand",
    "aniwœn": "anyone",
    "arro": "air",
    "arroflia": "plane, aeroplane",
    "arss": "arse, bottom",
    "azol": "apple",
    "azonom": "astronomy",

    "bagir": "bag, backpack",
    "bai": "bye, goodbye",
    "bakk": "back (informal)",
    "band": "music band",
    "bas": "pass",
    "basik": "basic",
    "bii": "be",
    "biolot": "biology",
    "blonat": "planet",
    "blœ": "blue",
    "bost": "burst",
    "bœk": "back",
    "bro": "bro",
    "brœd": "bread",
    "bwas": "place, location",

    "dai": "day",
    "dat": "that",
    "dho": "but, though, although",
    "di": "the",
    "did": "did",
    "diksonri": "dictionary",
    "dira": "ten",
    "dis": "this",
    "dizital": "digital",
    "do": "do",
    "dodd": "jump",
    "dog": "dog",
    "donn": "down",
    "dos": "two",

    "drink": "drink",

    "faarr": "far",
    "fiind": "friend",
    "fim": "five",
    "fisi": "body, physical",
    "fisiks": "physics",
    "flaim": "fire, flame",
    "flia": "fly",
    "fliat": "flight",
    "fokos": "focus",
    "fol": "multiply, -fold",
    "fon": "phone",
    "for": "for",
    "fostiwit": "festival",
    "fœr": "four",
    "fridom": "freedom",
    "from": "from",
    "frœk": "frog",

    "gaii": "gay, lesbian (informal)",
    "gais": "guys",
    "gako": "nine",
    "gali": "hundred",
    "gamm": "game",
    "gati": "gay, lesbian (formal)",
    "giid": "guide",
    "git": "get, bring",
    "gœdidag": "good day",
    "gœdimorgin": "good morning",
    "gœdisiz": "good night",
    "gœlli": "LGBTQ+",
    "gratol": "grateful, thankful",
    "grœ": "grow",

    "haab": "have",
    "habibi": "friend",
    "hai": "hi",
    "hallœ": "hello",
    "haos": "house",
    "haz": "him",
    "hiirr": "here",
    "hiiz": "his",
    "hiz": "he",
    "hobisiz": "happiness",
    "hobiz": "happy",
    "hosi": "use, using",
    "hœ": "how",

    "i": "I",
    "id": "it",
    "if": "if",
    "iiti": "eight",
    "ik": "I'm",
    "ikonos": "economy",
    "ikonoset": "economic",
    "iksban": "expand",
    "iksimit": "excitement",
    "iksit": "excite",
    "iksitid": "excited",
    "ikt": "eat",
    "imii": "me, my, myself",
    "in": "in",
    "indizandis": "independence (informal)",
    "innowi": "innovation",
    "intirnaizono": "international",
    "is": "is",
    "issra": "independent",
    "issranis": "independence",
    "isst": "east",
    "ist": "is (alt)",
    "it": "it",
    "itoldai": "yesterday",
    "itt": "eat",
    "iz": "its",

    "kal": "call",
    "kammo": "camp",
    "kan": "night",
    "kimistri": "chemistry",
    "kobkradd": "frog",
    "kold": "cold",
    "kommbotar": "computer",
    "kommbotat": "computation, computational",
    "konna": "gonna",
    "kontinœ": "continue",
    "kontinœli": "continuous",
    "kontis": "contest",
    "korri": "curry",
    "korrot": "correction",
    "kœll": "cool",
    "krosi": "nearby",

    "labt": "laptop",
    "lah": "yes",
    "laii": "lie",
    "lasœksan": "congratulations",
    "ligind": "legend",
    "ligindo": "legendary",
    "liif": "life",
    "liik": "like",
    "liwisi": "revision",
    "low": "low, little",
    "lowin": "reduce",
    "loz": "love",
    "le": "the (less common)",

    "maazik": "magic",
    "maazikal": "magical",
    "math": "math",
    "mathi": "mathematical",
    "mathi narizbikkolim": "prestigious mathematical olympiad",
    "mi": "question indicator",
    "mian": "mean",
    "midt": "meet",
    "midttaab": "meetup",
    "midwi": "middle",
    "midwidai": "midday",
    "midwikan": "midnight",
    "mika": "cloud",
    "milk": "milk",
    "mobilfon": "smartphone",
    "monniz": "money",
    "mœrnin": "morning",

    "nai": "no, not",
    "naifol": "divide",
    "naigi": "negative",
    "naiwi": "black",
    "naizon": "nation",
    "naizono": "national",
    "narizbikk": "prestigious",
    "narizbikkolim": "prestigious contest",
    "nasœksan": "enjoyable",
    "nidi": "subtract",
    "niida": "need",
    "niw": "new",
    "niwbi": "newbie",
    "nol": "none",
    "nott": "north",

    "ob": "up",
    "od": "old",
    "of": "of",
    "ok": "okay",
    "okaii": "okay",
    "oktaldai": "day before yesterday",
    "olimmna": "Olympics",
    "ond": "and",
    "onn": "on",
    "orwiti": "orbit",
    "ot": "or",
    "otdat": "update",
    "otdatid": "updated",
    "ottimmo": "utmost",

    "radi": "red",
    "radiz": "radish",
    "rados": "radius",
    "riiwo": "revolve",
    "riliks": "relax",
    "rilozi": "religion",
    "rirondai": "day after tomorrow",
    "risti": "rest",
    "risz": "rizz (singular)",
    "riwisi": "revision",
    "rizbik": "respect",
    "robzil": "picture",
    "rondai": "tomorrow",
    "rœn": "tree",

    "saats": "south",
    "sai": "say, tell",
    "saio": "left",
    "salo": "right",
    "samad": "smart",
    "samid": "summit",
    "saz": "her",
    "shatin": "chatting",
    "sid": "she",
    "siid": "hers",
    "siiz": "science",
    "siizi": "scientific",
    "siiz narizbikk olimmna": "prestigious science olympiad",
    "sikma": "sigma",
    "siks": "six",
    "siks-sion": "six seven (slang)",
    "sion": "seven",
    "siro": "zero",
    "sitmir": "statement",
    "skœl": "school",
    "snatz": "snatch",
    "snazr": "snatcher",
    "sord": "sorry",
    "sœitar": "super",
    "sœksana": "merry",
    "sœt": "should",
    "star": "star",
    "stato": "statue",
    "stil": "still",
    "stillwassir": "still water",
    "ston": "stone",

    "tabfon": "tablet",
    "takk": "take",
    "tamminno": "million",
    "tanno": "thousand",
    "taz": "them",
    "thikk": "thick",
    "ti": "yes",
    "tiim": "team, group",
    "tiiz": "theirs",
    "tirbrik": "relieved",
    "tishir": "teacher",
    "tisti": "exam",
    "tiz": "they",
    "to": "to",
    "toldai": "today",
    "tri": "three",

    "want": "want",
    "was": "what",
    "wassir": "water",
    "wii": "we",
    "wiid": "wide",
    "wiir": "wire",
    "wiirnai": "wireless",
    "wik": "week",
    "wikiin": "weekend",
    "win": "win",
    "wirsin": "version",
    "wisst": "west",
    "wit": "white",
    "witt": "with",
    "wiz": "hope",
    "wizif": "hopeful",
    "woniit": "unite",
    "woniiti": "unity",
    "wœ": "you",
    "wœn": "one",

    "za": "yes",
    "zad": "them (non-binary)",
    "zam": "charm",
    "zamœl": "jamal",
    "zamœlin": "jamaling",
    "zas": "just",
    "zid": "they (non-binary)",
    "ziid": "their (non-binary)",
    "zill": "chill",
    "zilod": "yellow"
}

english_to_jamalese = {}
for jam, eng in jamalese_to_english.items():
    for meaning in [m.strip() for m in eng.split(",")]:
        english_to_jamalese.setdefault(meaning, []).append(jam)
